version: '3'

services:
  minio:
    image: bitnami/minio:2022
    networks: ['wlands']
    volumes: ['minio_data:/data']
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_SERVER_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SERVER_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=wlands,wlands-updates
      - MINIO_SERVER_HOST=http://127.0.0.1:11080
      - MINIO_BROWSER_REDIRECT_URL=${MINIO_BROWSER_REDIRECT_URL}
    restart: unless-stopped
  mariadb:
    image: mariadb:10.6
    networks: ['wlands']
    volumes: ['mariadb_data:/var/lib/mysql']
    environment:
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MARIADB_DATABASE=wlands
      - MARIADB_USER=${MYSQL_USER}
      - MARIADB_PASSWORD=${MYSQL_PASSWORD}
    restart: unless-stopped
  wlands-api:
    build: .
    networks: ['wlands']
    volumes: ['./keys:/wlands/keys', '${MIGRATIONS_VOLUME}:/migrations']
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mariadb/wlands
      - S3_ENDPOINT=http://minio:9000
      - S3_ENDPOINT_PUBLIC=${MINIO_SERVER_HOST}
      - S3_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - S3_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - SET_UPDATES_BUCKET_POLICY=${SET_UPDATES_BUCKET_POLICY}
      - MIGRATIONS_DIR=/migrations/wlands
    depends_on:
      - minio
      - mariadb
    restart: unless-stopped
  wlands-api-internal:
    build: .
    entrypoint: /wlands/entrypoint-internal.sh
    networks: ['wlands']
    volumes: ['./keys:/wlands/keys']
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mariadb/wlands
      - INTERNAL_AUTH_TOKEN=${INTERNAL_AUTH_TOKEN}
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - S3_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
    depends_on: [wlands-api]
    restart: unless-stopped
  nginx:
    image: nginx
    ports:
      - '${NGINX_ADDRESS}:80'
    networks: ['wlands']
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on: [wlands-api]
    restart: unless-stopped

networks:
  wlands:
    driver: bridge

volumes:
  minio_data:
    driver: local
  mariadb_data:
    driver: local
  migrations:
    driver: local