services:
  minio:
    image: bitnami/minio:2024
    networks: ['wlands']
    volumes: ['minio_data:/bitnami/minio/data']
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_SERVER_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SERVER_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=wlands,wlands-files
      - MINIO_SERVER_HOST=http://127.0.0.1:11080
      - MINIO_BROWSER_REDIRECT_URL=${MINIO_BROWSER_REDIRECT_URL}
    restart: unless-stopped
    healthcheck:
      test: mc ready local
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
  mariadb:
    image: mariadb:10.6
    networks: ['wlands']
    volumes: ['mariadb_data:/var/lib/mysql']
    environment:
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MARIADB_DATABASE=wlands
      - MARIADB_USER=${MYSQL_USER}
      - MARIADB_PASSWORD=${MYSQL_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: mysqladmin ping -h localhost
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 10
  wlands-api:
    build: .
    pull_policy: build
    networks: ['wlands']
    volumes: ['./keys:/wlands/keys', '${MIGRATIONS_VOLUME}:/migrations']
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mariadb/wlands
      - S3_ENDPOINT=http://minio:9000
      - S3_ENDPOINT_PUBLIC=${MINIO_SERVER_HOST}
      - S3_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - S3_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - SET_UPDATES_BUCKET_POLICY=${SET_UPDATES_BUCKET_POLICY}
      - MIGRATIONS_DIR=/migrations/wlands
      - ROOT_PATH=/api
    depends_on:
      mariadb:
        condition: service_healthy
      minio:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://127.0.0.1:8080/health || exit 1
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 10
  wlands-api-internal:
    build: .
    pull_policy: build
    command: /wlands/entrypoint-internal.sh
    networks: ['wlands']
    volumes: ['./keys:/wlands/keys']
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mariadb/wlands
      - INTERNAL_AUTH_TOKEN=${INTERNAL_AUTH_TOKEN}
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - S3_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
    depends_on:
      wlands-api:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://127.0.0.1:9080/health || exit 1
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 10
  nginx:
    image: nginx
    ports:
      - '${NGINX_ADDRESS}:80'
    networks: ['wlands']
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      wlands-api:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://127.0.0.1:80/healthcheck || exit 1
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  wlands:
    driver: bridge

volumes:
  minio_data:
    driver: local
  mariadb_data:
    driver: local
  migrations:
    driver: local