name: Pytest
on:
  pull_request:
    types: [opened]
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        # "3.13t" and "3.14t" are not supported
        #  because pydantic (and maybe other packages) don't support free-threaded python
        python-version: ["3.11", "3.12", "3.13", "3.14"]
      fail-fast: true

    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          restore-cache: true
          save-cache: true

      - name: Install dependencies
        run: |
          uv sync --locked --all-groups --all-extras --dev

      - name: Generate keypair
        run: |
          openssl genrsa -out keys/private.pem 2048
          openssl rsa -in keys/private.pem -pubout -out keys/public.pem

      - name: Run tests
        run: |
          uv run pytest --disable-warnings tests
        env:
          DATABASE_URL: "sqlite://:memory:"
          S3_ENDPOINT: "http://127.0.0.1:60080"
          S3_ACCESS_KEY_ID: "key_id"
          S3_SECRET_ACCESS_KEY: "access_key"

      - name: Print coverage report
        run: |
          uv run coverage report

      #- name: Upload coverage reports to Codecov
      #  uses: codecov/codecov-action@v5
      #  with:
      #    token: ${{ secrets.CODECOV_TOKEN }}